// <auto-generated by="the Blazor I18n Text compiler" />
namespace BLAZOR.UI.I18nText
{
    public partial class text : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "en";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>"Categories"</summary>
        public string Categorias;

        /// <summary>"Kids"</summary>
        public string Chicos;

        /// <summary>"Sports"</summary>
        public string Deportes;

        /// <summary>"Man"</summary>
        public string Hombre;

        /// <summary>"Logs"</summary>
        public string Logs;

        /// <summary>"Brands"</summary>
        public string Marcas;

        /// <summary>"Woman"</summary>
        public string Mujer;

        /// <summary>"Sales"</summary>
        public string Ofertas;

        /// <summary>"Products"</summary>
        public string Productos;

        /// <summary>"Stores"</summary>
        public string Sucursales;

        /// <summary>"Sell"</summary>
        public string Vender;
    }
}
